AWSTemplateFormatVersion: '2010-09-09'
Description: MWFinancial - Security resources including ECS Execution Role and Security Group

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where resources will be deployed

Resources:

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  MWFinancialSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: mwfinancial-sg
      GroupDescription: Security group for MWFinancial services
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: mwfinancial-sg

Outputs:
  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref MWFinancialSecurityGroup

  ECSExecutionRoleArn:
    Description: ARN of the ECS execution role
    Value: !GetAtt ECSExecutionRole.Arn
