AWSTemplateFormatVersion: '2010-09-09'
Description: Security resources for MWFinancial System

Resources:

  MWFinancialSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound HTTP/HTTPS and outbound traffic
      VpcId: vpc-xxxxxxxx # Replace with your actual VPC ID or reference it via parameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:
  SecurityGroupId:
    Description: ID of the ECS Security Group
    Value: !Ref MWFinancialSecurityGroup

  ECSExecutionRoleArn:
    Description: ARN of the ECS Execution Role
    Value: !GetAtt ECSExecutionRole.Arn
